fix

diff --git a/.github/workflows/pre-submit-test.yaml b/.github/workflows/pre-submit-test.yaml
--- a/.github/workflows/pre-submit-test.yaml
+++ b/.github/workflows/pre-submit-test.yaml
@@ -7,7 +7,27 @@ on:
       - edited
       - synchronize
 jobs:
+  TestIntegrityCheck:
+    runs-on: ubuntu-latest
+    if: ${{ startsWith(github.head_ref, 'networking_ex/')  }}
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{github.event.pull_request.head.ref}}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+      - name: Check tests integrity
+        run: |
+          H=$(find projects/bash_networking_security/test/ -type f -exec md5sum {} + | awk '{print $1}' | sort | md5sum | awk '{print $1}')
+
+          echo "Your tests hash is $H" 
+
+          if [ "$H" != "27c001c54ad7bd41bf4781f947914489" ]
+          then
+            echo "Test integrity failed. Make sure your PR has not changes the 'test' directory."
+            exit 1
+          fi
   NetworkingExTestBastionRotation:
+    needs: [TestIntegrityCheck]
     runs-on: ubuntu-latest
     if: ${{ startsWith(github.head_ref, 'networking_ex/')  }}
     env:
@@ -19,17 +39,6 @@ jobs:
         with:
           ref: ${{github.event.pull_request.head.ref}}
           repository: ${{github.event.pull_request.head.repo.full_name}}
-      - name: Check tests integrity
-        run: | 
-          H=$(find projects/bash_networking_security/test/ -type f -exec md5sum {} + | awk '{print $1}' | sort | md5sum | awk '{print $1}')
-          
-          echo "Your tests hash is $H" 
-          
-          if [ "$H" != "27c001c54ad7bd41bf4781f947914489" ]
-          then
-            echo "Test integrity failed. Make sure your PR has not changes the 'test' directory."
-            exit 1
-          fi
       - uses: hashicorp/setup-terraform@v2
       - name: Networking Ex - VPC Check
         run: |
@@ -46,6 +55,7 @@ jobs:
           cd projects/bash_networking_security/test
           bash test_rotation.sh
   NetworkingExTestTLSHandshake:
+    needs: [ TestIntegrityCheck ]
     runs-on: ubuntu-latest
     if: ${{ startsWith(github.head_ref, 'networking_ex/')  }}
     env:
